import Description from "@/components/description"
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import Head from "next/head"
import Card from "./landingpage/Card"
import Card_2 from "./landingpage/Card_2"
import Carousel from "./landingpage/Carousel"
import Middle from "./landingpage/Middle"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Carousel />
      <Card />
      <Middle />
      <Card_2 />
      <Description />
      <Footer />
    </>
  )
}
